name: FE Docker Image CI

on:
  push:
    tags: 
      - v** 

jobs:

  build-fe:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the frontend Docker image
      run: docker build . --file ./BlazorApp1/Dockerfile --tag edelbitter/timetracking-fe:${{ github.ref_name }}
      
  build-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build the backend Docker image
        run: docker build . --file ./TimeTrackingBE/Dockerfile --tag edelbitter/timetracking-be:${{ github.ref_name }}
        
  push-images:
     needs: [build-fe,build-be]
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
           
       - name: Log in to Docker Hub
         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
         with:
             registry: ghcr.io
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}       
       
       - name: push fe images to docker hub
         run: docker push ghcr.io/edelbitter/timetracking-fe:${{ github.ref_name }}
       - name: push be image to docker hub
         run: docker push ghcr.io/edelbitter/timetracking-be:${{ github.ref_name }}
